name: aocc

on:
    # it works, disable automatic trigger for now
    workflow_dispatch:
        # push:
        #     branches: [ main ]
        # pull_request:

jobs:
    build:
        name: ci
        uses: ./.github/workflows/ci.yml

    integration-tests:
        name: ${{ matrix.toolchain.version }} ${{ matrix.image }} ${{
            matrix.toolchain.windowsEnv }}
        runs-on: ${{ matrix.image }}
        needs: [ build ]
        strategy:
            fail-fast: false
            matrix:
                image: [ ubuntu-24.04, ubuntu-22.04 ]

                toolchain:
                    - { compiler: aocc, version: "5.1" }
                    - { compiler: aocc, version: "5.0" }
                    - { compiler: aocc, version: "4.2" }
                    - { compiler: aocc, version: "4.1" }

        steps:
            - uses: actions/checkout@v6

            - name: Restore dist-tests
              uses: actions/download-artifact@v8
              with:
                  name: generated-dist-tests
                  path: dist-tests

            - name: Install ${{ matrix.toolchain.compiler }} ${{ matrix.toolchain.version }}
              id: setup
              uses: ./
              with:
                  compiler: ${{ matrix.toolchain.compiler }}
                  version: ${{ matrix.toolchain.version }}

            - name: Verify installed version
              run: "echo \"Output: ${{ steps.setup.outputs.version }}\""

            - name: Run Integration Tests
              run: npm run integration-test
